---
- name: Vault Provisioning
  hosts: all
  remote_user: darkirondan
  become: yes

  vars:
        unseal_keys_dir_output: "{{ playbook_dir }}/unsealKey"
        root_token_dir_output: "{{ playbook_dir }}/rootKey"
  roles:
    - vault_provisioning
