name: CI
on:
  workflow_dispatch:
    branches:
    - main

jobs:
  linux:
    name: Build and deploy to k8s
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: build and deploy images.
      run: "./deploy/k8s/helm/deploy_manual.sh"

    - name: Delevery changes of page.
      run: "./deploy/k8s/helm/deploy-all-mac.ps1 -externalDns aks -aksName ctn-cluster -aksRg ctn-k8s -imageTag linux-latest -registry acr0tf.azurecr.io -dockerUser acr0tf -dockerPassword dm3NuH4FwMyyBJ3b/ouUEwYRJWMScxzQ -useMesh $false"